// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mio-api.proto

package com.mio.mioapigateway.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseData = 1;</code>
   * @return The responseData.
   */
  String getResponseData();
  /**
   * <code>string responseData = 1;</code>
   * @return The bytes for responseData.
   */
  com.google.protobuf.ByteString
      getResponseDataBytes();
}
